-- 코드를 입력하세요 : 이 아래는 시행착오
-- SELECT FIRST_HALF.FLAVOR, FIRST_HALF.TOTAL_ORDER, JULY.FLAVOR, JULY.TOTAL_ORDER, sum(JULY.TOTAL_ORDER), FIRST_HALF.TOTAL_ORDER+sum(JULY.TOTAL_ORDER)
-- FROM FIRST_HALF RIGHT JOIN JULY ON FIRST_HALF.FLAVOR = JULY.FLAVOR
-- GROUP BY JULY.FLAVOR
-- ORDER BY FIRST_HALF.TOTAL_ORDER+sum(JULY.TOTAL_ORDER) DESC;

SELECT JULY.FLAVOR
FROM FIRST_HALF RIGHT JOIN JULY ON FIRST_HALF.FLAVOR = JULY.FLAVOR
GROUP BY JULY.FLAVOR
ORDER BY FIRST_HALF.TOTAL_ORDER+sum(JULY.TOTAL_ORDER) DESC
LIMIT 3;