-- 코드를 입력하세요
SELECT BOOK.CATEGORY AS 'CATEGORY', SUM(BOOK_SALES.SALES) AS 'TOTAL_SALES'
FROM BOOK_SALES JOIN BOOK ON BOOK_SALES.BOOK_ID=BOOK.BOOK_ID
WHERE YEAR(BOOK_SALES.SALES_DATE)=2022 AND MONTH(BOOK_SALES.SALES_DATE)=1
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY ASC;